services:
  bot:
    container_name: dating-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VK_ACCESS_TOKEN: ${DATING_VK_ACCESS_TOKEN?:err}
      VK_GROUP_ID: ${DATING_VK_GROUP_ID?:err}
      VK_ADMIN_CHAT_ID: ${DATING_VK_ADMIN_CHAT_ID?:err}
      VK_ADMIN_ID: ${DATING_VK_ADMIN_ID?:err}
      DATABASE_URL: ${DATING_DATABASE_URL?:err}
    volumes:
      - ./data/blacklist.txt:/usr/src/app/data/blacklist.txt
    depends_on:
      database:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 4
        window: 16s
    networks:
      - dating-network

  database:
    container_name: dating-database
    image: postgres
    environment:
      PGUSER: ${DATING_POSTGRES_USER?:err}
      POSTGRES_DB: ${DATING_POSTGRES_DATABASE?:err}
      POSTGRES_USER: ${DATING_POSTGRES_USER?:err}
      POSTGRES_PASSWORD: ${DATING_POSTGRES_PASSWORD?:err}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - dating-network

networks:
  dating-network:
    driver: bridge
